name: "Terragrunt Destroy"

on:
  workflow_dispatch: # 手动触发，避免意外删除生产环境

permissions:
  id-token: write
  contents: read

jobs:
  terragrunt-destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure-live
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} 
          aws-region: us-east-1

      - name: Setup Terraform & Terragrunt
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
      
      - name: Install Terragrunt
        run: |
          TG_VERSION=$(curl -s "https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
          curl -L "https://github.com/gruntwork-io/terragrunt/releases/download/${TG_VERSION}/terragrunt_linux_amd64" -o terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt

      - name: Terragrunt Destroy
        run: |
          # stage 1 destroy all the EC2 Instances
          echo "--- Phase 1: Destroying EC2 Instances ---"
          EC2_MODULES=("dev/ec2" "prod/ec2")
          for module in "${EC2_MODULES[@]}"; do
            echo "--- Destroying EC2: $module ---"
            cd $module
            rm -rf .terragrunt-cache
            terragrunt init -reconfigure -no-color
            terragrunt destroy -auto-approve -no-color
            cd $GITHUB_WORKSPACE/infrastructure-live
          done

          # stage 2 delete all the VPCs
          echo "--- Phase 2: Destroying VPCs ---"
          VPC_MODULES=("dev/vpc" "test/vpc" "stage/vpc" "prod/vpc")
          for module in "${VPC_MODULES[@]}"; do
            echo "--- Destroying VPC: $module ---"
            cd $module
            rm -rf .terragrunt-cache
            terragrunt init -reconfigure -no-color
            
            terragrunt destroy -target=aws_nat_gateway.main -auto-approve -no-color || true
            
            terragrunt destroy -auto-approve -no-color
            cd $GITHUB_WORKSPACE/infrastructure-live
          done
        env:
          TG_NON_INTERACTIVE: "true"